<?php

/**
 * WpCommentmetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpCommentmetaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpCommentmetaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpCommentmeta');
    }
}