<?php
/**
 * WpHerissonFriendsTable
 * 
 * @category Models
 * @package  Herisson
 * @author   Thibault Taillandier <thibault@taillandier.name>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPL v3
 * @link     None
 */

/**
 * ORM class to handle the database table relation.
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * It contains static methods to request the database.
 *
 * @category Models
 * @package  Herisson
 * @author   Thibault Taillandier <thibault@taillandier.name>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPL v3
 * @link     None
 */
class WpHerissonFriendsTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object WpHerissonFriendsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpHerissonFriends');
    }


    /**
     * Get the WpHerissonFriends match the id
     *
     * @param integer $friendId the id of the friend
     *
     * @return the matching WpHerissonFriends or new one
     */
    public static function get($friendId)
    {
        if (!is_numeric($friendId)) {
            return new WpHerissonFriends();
        }
        $friends = Doctrine_Query::create()
            ->from('WpHerissonFriends')
            ->where("id=?")
            ->execute(array($friendId));
        foreach ($friends as $friend) {
            return $friend;
        }
        return new WpHerissonFriends();
    }


    /**
     * Get a WpHerissonFriends list with where condition
     *
     * @param string $where the sql condition
     * @param array  $data  the value parameters
     *
     * @return an array of matching WpHerissonFriends
     */
    public static function getWhere($where, $data=array())
    {
        $pagination = HerissonPagination::i()->getVars();
        $friends = Doctrine_Query::create()
            ->from('WpHerissonFriends')
            ->where($where)
            ->limit($pagination['limit'])
            ->offset($pagination['offset'])
            ->execute($data);
        return $friends;
    }


    /**
     * Get one item with where paremeters
     *
     * @param string $where the sql condition
     * @param array  $data  the value parameters
     *
     * @return the corresponding instance of WpHerissonFriends or a new one
     */
    public static function getOneWhere($where, $data=array())
    {
        $friends = Doctrine_Query::create()
            ->from('WpHerissonFriends')
            ->where($where)
            ->limit(1)
            ->execute($data);
        foreach ($friends as $friend) {
            return $friend;
        }
        return new WpHerissonFriends();
    }


}
