<?php

/**
 * WpHerissonTags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WpHerissonTags extends BaseWpHerissonTags
{

# public function setUp()
# {
#  parent::setUp();
#  $this->hasMany('WpHerissonBookmarks', array(
#   'local' => 'bookmark_id',
#   'foreign' => 'id'));
# }
}
