<?php

/**
 * WpHerissonScreenshotsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpHerissonScreenshotsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpHerissonScreenshotsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpHerissonScreenshots');
    }
}
