<?php

/**
 * WpHerissonFriendsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpHerissonFriendsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpHerissonFriendsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpHerissonFriends');
    }

    public static function getWhere($where)
    {
        $pagination = pagination_get_vars();
        $friends = Doctrine_Query::create()
            ->from('WpHerissonFriends')
            ->where($where)
            ->limit($pagination['limit'])
            ->offset($pagination['offset'])
            ->execute();
        return $friends;
    }


}
