<?php

/**
 * WpHerissonTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpHerissonTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpHerissonTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpHerissonTags');
    }

    public static function getAll()
    {
        // select count(*) as c ,name from wp_herisson_tags group by name order by name;
        return Doctrine_Query::create()
            ->select('count(*) as c, name')
            ->from('WpHerissonTags')
            ->groupby('name')
            ->orderby('name')
            ->execute();
    }
}
