<?php

/**
 * WpTermRelationshipsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpTermRelationshipsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpTermRelationshipsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpTermRelationships');
    }
}