<?php

/**
 * WpTermsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpTermsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpTermsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpTerms');
    }
}