<?php

/**
 * WpHerissonBackupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpHerissonBackupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpHerissonBackupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpHerissonBackups');
    }
}
