<?php

/**
 * WpHerissonTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpHerissonTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpHerissonTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpHerissonTypes');
    }
}
