<?php
/**
 * WpHerissonLocalbackupsTable
 * 
 * @category Models
 * @package  Herisson
 * @author   Thibault Taillandier <thibault@taillandier.name>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPL v3
 * @link     None
 */

namespace Herisson\Model;

use Doctrine_Query;
use Doctrine_Table;
use Doctrine_Core;

use Herisson\Pagination;

/**
 * ORM class to handle the database table relation.
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * It contains static methods to request the database.
 *
 * @category Models
 * @package  Herisson
 * @author   Thibault Taillandier <thibault@taillandier.name>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPL v3
 * @link     None
 */
class WpHerissonLocalbackupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpHerissonLocalbackupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpHerissonLocalbackups');
    }

    /**
     * Get the WpHerissonLocalbackups match the id
     *
     * @param integer $backupId the id of the backup
     *
     * @return the matching WpHerissonLocalbackups or new one
     */
    public static function get($backupId)
    {
        if (!is_numeric($backupId)) {
            return new WpHerissonLocalbackups();
        }
        return self::getOneWhere("id=?", array($backupId));
    }

    /**
     * Get a WpHerissonLocalbackups list with where condition
     *
     * @param string $where the sql condition
     * @param array  $data  the value parameters
     *
     * @return an array of matching WpHerissonLocalbackups
     */
    public static function getWhere($where, $data=array())
    {
        $pagination = Pagination::i()->getVars();
        $backups = Doctrine_Query::create()
            ->from('Herisson\Model\WpHerissonLocalbackups')
            ->where($where)
            ->limit($pagination['limit'])
            ->offset($pagination['offset'])
            ->execute($data);
        return $backups;
    }


    /**
     * Get one item with where paremeters
     *
     * @param string $where the sql condition
     * @param array  $data  the value parameters
     *
     * @return the corresponding instance of WpHerissonLocalbackups or a new one
     */
    public static function getOneWhere($where, $data=array())
    {
        $backups = Doctrine_Query::create()
            ->from('Herisson\Model\WpHerissonLocalbackups')
            ->where($where)
            ->limit(1)
            ->execute($data);
        foreach ($backups as $backup) {
            return $backup;
        }
        return new WpHerissonLocalbackups();
    }

}
