<?php

/**
 * WpHerissonLocalbackupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpHerissonLocalbackupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpHerissonLocalbackupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpHerissonLocalbackups');
    }
}