<?php
/**
 * WpHerissonScreenshots
 * 
 * @category Models
 * @package  Herisson
 * @author   Thibault Taillandier <thibault@taillandier.name>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPL v3
 * @link     None
 */

namespace Herisson\Model;

/**
 * WpHerissonScreenshots
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @category Models
 * @package  Herisson
 * @author   Thibault Taillandier <thibault@taillandier.name>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPL v3
 * @link     None
 */
class WpHerissonScreenshots extends \BaseWpHerissonScreenshots
{

}

