<?php
/**
 * WpHerissonLocalbackupsTable
 * 
 * @category Models
 * @package  Herisson
 * @author   Thibault Taillandier <thibault@taillandier.name>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPL v3
 * @link     None
 */

namespace Herisson\Model;

/**
 * ORM class to handle the database table relation.
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * It contains static methods to request the database.
 *
 * @category Models
 * @package  Herisson
 * @author   Thibault Taillandier <thibault@taillandier.name>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPL v3
 * @link     None
 */
class WpHerissonLocalbackups extends \BaseWpHerissonLocalbackups
{

}
