<?php
/**
 * WpHerissonTags
 * 
 * @category Models
 * @package  Herisson
 * @author   Thibault Taillandier <thibault@taillandier.name>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPL v3
 * @link     None
 */

/*
namespace Herisson\Model;

use Doctrine_Query;
use Doctrine_Table;
use Doctrine_Core;
 */

/**
 * WpHerissonTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @category Models
 * @package  Herisson
 * @author   Thibault Taillandier <thibault@taillandier.name>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPL v3
 * @link     None
 */
class WpHerissonTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpHerissonTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpHerissonTags');
    }

    /**
     * Get all tags from database
     *
     * @return the list of all tags with their count
     */
    public static function getAll()
    {
        return Doctrine_Query::create()
            ->select('count(*) as c, name')
            ->from('WpHerissonTags')
            ->groupby('name')
            ->orderby('name')
            ->execute();
    }
}
