<?php

/**
 * WpHerissonBookmarks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WpHerissonBookmarks extends BaseWpHerissonBookmarks
{

 public function setUrl($url) {
  parent::_set('url',$url);
		$this->reloadContent();
 }

 public function setTitle($title) {
  parent::_set('title',$title);
  $this->_set('hash',md5($title));
 }

	public function reloadContent() {
	 $url = $this->_get('url');
  if (function_exists('curl_init')) {

   $curl = curl_init();
   curl_setopt($curl, CURLOPT_URL, $url);
   curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

   $content = curl_exec($curl);
   $this->_set('content',$content);
  }
	}

	public function toArray() {
	 return array(
		 "title" => $this->title,
		 "url" => $this->url,
		 "description" => $this->description,
		);

	}

}
