<?php

/**
 * WpHerissonBookmarks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WpHerissonBookmarks extends BaseWpHerissonBookmarks
{

 public function setUrl($url) {
  parent::_set('url',$url);
 	$this->reloadContent();
 	$this->capture();
 }

 public function setTitle($title) {
  parent::_set('title',$title);
  $this->_set('hash',md5($title));
 }

	public function reloadContent() {
		if (!$this->content) {
		 $content = herisson_download($this->url);
 		if (!is_wp_error($content)) {
    $this->_set('content',$content);
 		} else { 
 			echo $data->get_error_message("herisson");
 		}
  }
	}

	public function toArray() {
	 return array(
		 "title" => $this->title,
		 "url" => $this->url,
		 "description" => $this->description,
		);
	}
 
	public function getThumbUrl() {
	 return get_option('siteurl')."/wp-content/plugins/herisson/screenshots/".$this->id."_small.png";
	}

	public function getImageUrl() {
	 return get_option('siteurl')."/wp-content/plugins/herisson/screenshots/".$this->id.".png";
	}

	public function getThumb() {
	 return HERISSON_SCREENSHOTS_DIR.$this->id."_small.png";
	}

	public function getImage() {
	 return HERISSON_SCREENSHOTS_DIR.$this->id.".png";
	}

	public function capture() {
	 if (!$this->id) { return false; }
	 # ./wkhtmltoimage-amd64 --disable-javascript --quality 50 http://www.wilkins.fr/ /home/web/www.wilkins.fr/google.png
		$url = $this->url;
		$image = HERISSON_SCREENSHOTS_DIR.$this->id.".png";
		$thumb = HERISSON_SCREENSHOTS_DIR.$this->id."_small.png";
		$wkhtmltoimage = HERISSON_BASE_DIR."wkhtmltoimage-amd64";
		$convert = "/usr/bin/convert";
		$options_nojs = " --disable-javascript ";
		$options_quality50 = " --quality 50 ";
		if (!file_exists($image) || filesize($image) == 0) {
# 		echo "$wkhtmltoimage $options_quality50 \"$url\" $image";
 		exec("$wkhtmltoimage $options_quality50 \"$url\" $image",$output);
		 echo implode("\n",$output);
		}

		if (!file_exists($image) || filesize($image) == 0) {
# 		echo "$wkhtmltoimage $options_nojs $options_quality50 \"$url\" $image";
 		exec("$wkhtmltoimage $options_nojs $options_quality50 \"$url\" $image",$output);
		 echo implode("\n",$output);
		}

		if (!file_exists($thumb) || filesize($thumb) == 0) {
 		exec("$convert -resize 200x \"$image\" \"$thumb\"",$output);
		 echo implode("\n",$output);
		}

	}

}
