<?php

/**
 * WpHerissonFriends
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WpHerissonFriends extends BaseWpHerissonFriends
{

 public function setUrl($url) {
  parent::_set('url',$url);
		$this->reloadPublicKey();
 }

	public function reloadPublicKey() {
	 $url = $this->_get('url');
		if (substr($url, -1) != "/") {	$url .= "/"; }
		$url .= "publickey";
  if (function_exists('curl_init')) {

   $curl = curl_init();
   curl_setopt($curl, CURLOPT_URL, $url);
   curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
   curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);

   $content = curl_exec($curl);
   $this->_set('public_key',$content);
  }
	}


	public function retrieveBookmarks() {
	 
	 $options = get_option('HerissonOptions');
		$my_public_key = $options['publicKey'];
  if (function_exists('curl_init')) {
 		$data = array('key' => $my_public_key);

   $curl = curl_init();
   curl_setopt($curl, CURLOPT_URL, $this->url."/retrieve");
   curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
   curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
	  curl_setopt($curl, CURLOPT_POST,TRUE);
	  curl_setopt($curl, CURLOPT_POSTFIELDS,$data);


   $content = curl_exec($curl);
			$json_data = herisson_decrypt($content,$this->public_key);
			$bookmarks = json_decode($json_data,1);
   return $bookmarks;
  }
	}

 public function generateBookmarksdata() {
  $data_bookmarks = array();
  $bookmarks = Doctrine_Query::create()
   ->from('WpHerissonBookmarks')
   ->where('is_public=1')
   ->execute();
  foreach ($bookmarks as $bookmark) {
   $data_bookmarks[] = $bookmark->toArray();
  }
  $json_data = json_encode($data_bookmarks);
#  print_r($json_data);
  $json_display = herisson_encrypt($json_data,$this->public_key);
  return json_encode($json_display);
 }

}
