<?php

/**
 * WpHerissonBookmarksTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpHerissonBookmarksTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpHerissonBookmarksTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpHerissonBookmarksTags');
    }
}