<?php

/**
 * WpHerissonFriends
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WpHerissonFriends extends BaseWpHerissonFriends
{

 public function setUrl($url) {
  parent::_set('url',$url);
		$this->reloadPublicKey();
 }

	public function reloadPublicKey() {
	 $url = $this->_get('url');
		$url = $url."//publickey";
		$url = preg_replace("#//+#","/",$url);
  if (function_exists('curl_init')) {

#   $url ="http://japon.taillandier.name/bookmarks";
#			echo "---$url---<br>\n";
   $curl = curl_init();
   curl_setopt($curl, CURLOPT_URL, $url);
   curl_setopt($curl, CURLOPT_HEADER, 1);
   curl_setopt($curl, CURLOPT_VERBOSE, true);
   curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

   $content = curl_exec($curl);
   $this->_set('public_key',$content);
  }
	}


}
